name: 'Github Metrics'

description: 'Post Pull Request Metrics on Slack'

runs:
  # highest available version
  using: 'node12'
  main: 'dist/index.js'

inputs:
  github-owner:
    required: true
    description: 'Github Organisation Name'
  github-repo:
    required: true
    description: 'Github Repository Name'
  github-token:
    required: true
    description: 'Github API token to connect to Github'
  slack-app-token:
    required: true
    description: 'Slack Application Token'
  slack-channel-id:
    required: true
    description: 'Slack Channel Id'
