name: 'Github Metrics'

description: 'Post Pull Request Metrics on Slack'

runs:
  # highest available version
  using: 'node12'
  main: 'dist/index.js'

inputs:
  github-owner:
    required: true
    description: 'Github Organisation Name'
  github-repo:
    required: true
    description: 'Github Repository Name'
  github-token:
    required: true
    description: 'Github API token to connect to Github'
  slack-app-token:
    required: true
    description: 'Slack Application Token'
  slack-channel-id:
    required: true
    description: 'Slack Channel Id'
  log-debug-messages:
    required: false
    default: "false"
    description: Show all debug logs
  post-to-slack:
    required: false
    default: "true"
    description: Whether to post to slack
  config-yml:
    required: false
    default: ""
    description: "Configuration yml file"
